version: "3.0"

services:
  crm-backend:
    container_name: crm-backend
    image: node:12.16.1-alpine
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${APP_DEBUG_PORT}:${APP_DEBUG_PORT}
    env_file:
      - .env.dev
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - crm
    depends_on:
      - crm-mongodb
    command: npm run start:dev

  crm-mongodb:
    container_name: crm-mongodb
    image: mongo:3.6.21
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - crm


networks:
  crm:
    external: true
